CREATE TABLE IF NOT EXISTS student（
	`id` INT AUTO_INCREMENT PRIMARTY KEY,
	`name` VARCHAR(255) NOT NULL DEFAULT `` COMMENT `姓名`,
	`age` TINYINT NUSIGNED NOT NULL DEFAULT 0 COMMENT `年龄`,
	`sex` TINYINT UNSIGEND NOT NULL DEFAULT 10 COMMENT `性别`,
	`created_at` INT NOT NULL DEFAULT 0 COMMENT `新增时间`,
	`updated_at` INT NOT NULL DEFAULT 0 COMMENT `修改时间`
	)ENGINE=InnoDB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1001 COMMENT=`学生表`;
	
	CREATE TABLE IF NOT EXISTS student（
	`id` INT AUTO_INCREMENT PRIMARTY KEY,
	`name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT `姓名`,
	`age` TINYINT NUSIGNED NOT NULL DEFAULT 0 COMMENT `年龄`,
	`sex` TINYINT UNSIGEND NOT NULL DEFAULT 10 COMMENT `性别`,
	`created_at` INT NOT NULL DEFAULT 0 COMMENT `新增时间`,
	`updated_at` INT NOT NULL DEFAULT 0 COMMENT `修改时间`
	)ENGINE=InnoDB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1001 COMMENT=`学生表`;
	